language: node_js
node_js: 
  - "stable"
branches:
  only:
  - dev-ft
cache:
  directories:
    - "node_modules"
before_script:
  - npm run start
script:
  - npm test
after_success:
  - npm run coveralls